-- ============================================================
-- WINTOZO — ПОЛНЫЙ SQL
-- Выполни ВЕСЬ этот файл в Supabase SQL Editor за один раз
-- ============================================================

-- ============================================================
-- 1. ТАБЛИЦЫ ПОЛЬЗОВАТЕЛЕЙ И СООБЩЕНИЙ (ЛС)
-- ============================================================

CREATE TABLE IF NOT EXISTS wintozo_users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  avatar TEXT DEFAULT 'W',
  avatar_url TEXT,
  description TEXT DEFAULT '',
  banned BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wintozo_messages (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  from_user TEXT NOT NULL,
  to_user TEXT NOT NULL,
  text TEXT,
  image_url TEXT,
  audio_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE wintozo_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE wintozo_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "wintozo_users_read" ON wintozo_users;
DROP POLICY IF EXISTS "wintozo_users_insert" ON wintozo_users;
DROP POLICY IF EXISTS "wintozo_users_update" ON wintozo_users;
DROP POLICY IF EXISTS "wintozo_users_delete" ON wintozo_users;
DROP POLICY IF EXISTS "wintozo_messages_read" ON wintozo_messages;
DROP POLICY IF EXISTS "wintozo_messages_insert" ON wintozo_messages;
DROP POLICY IF EXISTS "wintozo_messages_delete" ON wintozo_messages;

CREATE POLICY "wintozo_users_read"   ON wintozo_users    FOR SELECT USING (true);
CREATE POLICY "wintozo_users_insert" ON wintozo_users    FOR INSERT WITH CHECK (true);
CREATE POLICY "wintozo_users_update" ON wintozo_users    FOR UPDATE USING (true);
CREATE POLICY "wintozo_users_delete" ON wintozo_users    FOR DELETE USING (true);
CREATE POLICY "wintozo_messages_read"   ON wintozo_messages FOR SELECT USING (true);
CREATE POLICY "wintozo_messages_insert" ON wintozo_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "wintozo_messages_delete" ON wintozo_messages FOR DELETE USING (true);

DO $$ BEGIN ALTER PUBLICATION supabase_realtime DROP TABLE wintozo_messages; EXCEPTION WHEN OTHERS THEN NULL; END $$;
ALTER PUBLICATION supabase_realtime ADD TABLE wintozo_messages;

-- ============================================================
-- 2. ГРУППЫ
-- ============================================================

-- BY DEFAULT — код вставляет id вручную из URL
CREATE TABLE IF NOT EXISTS wintozo_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT DEFAULT '',
  avatar_url TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wintozo_group_messages (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  from_user TEXT NOT NULL,
  text TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE wintozo_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE wintozo_group_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "groups_read" ON wintozo_groups;
DROP POLICY IF EXISTS "groups_insert" ON wintozo_groups;
DROP POLICY IF EXISTS "groups_update" ON wintozo_groups;
DROP POLICY IF EXISTS "group_msg_read" ON wintozo_group_messages;
DROP POLICY IF EXISTS "group_msg_insert" ON wintozo_group_messages;

CREATE POLICY "groups_read"      ON wintozo_groups          FOR SELECT USING (true);
CREATE POLICY "groups_insert"    ON wintozo_groups          FOR INSERT WITH CHECK (true);
CREATE POLICY "groups_update"    ON wintozo_groups          FOR UPDATE USING (true);
CREATE POLICY "group_msg_read"   ON wintozo_group_messages  FOR SELECT USING (true);
CREATE POLICY "group_msg_insert" ON wintozo_group_messages  FOR INSERT WITH CHECK (true);

DO $$ BEGIN ALTER PUBLICATION supabase_realtime DROP TABLE wintozo_groups; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime DROP TABLE wintozo_group_messages; EXCEPTION WHEN OTHERS THEN NULL; END $$;
ALTER PUBLICATION supabase_realtime ADD TABLE wintozo_groups;
ALTER PUBLICATION supabase_realtime ADD TABLE wintozo_group_messages;

-- ============================================================
-- 3. SOLNECHNAYA (старое приложение)
-- ============================================================

CREATE TABLE IF NOT EXISTS solnechnaya_users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  avatar TEXT DEFAULT '🌻',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS solnechnaya_messages (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  text TEXT NOT NULL,
  avatar TEXT DEFAULT '🌻',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE solnechnaya_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE solnechnaya_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "solnechnaya_read" ON solnechnaya_messages;
DROP POLICY IF EXISTS "solnechnaya_insert" ON solnechnaya_messages;
DROP POLICY IF EXISTS "solnechnaya_users_read" ON solnechnaya_users;
DROP POLICY IF EXISTS "solnechnaya_users_insert" ON solnechnaya_users;

CREATE POLICY "solnechnaya_read"        ON solnechnaya_messages FOR SELECT USING (true);
CREATE POLICY "solnechnaya_insert"      ON solnechnaya_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "solnechnaya_users_read"  ON solnechnaya_users    FOR SELECT USING (true);
CREATE POLICY "solnechnaya_users_insert" ON solnechnaya_users   FOR INSERT WITH CHECK (true);

DO $$ BEGIN ALTER PUBLICATION supabase_realtime DROP TABLE solnechnaya_messages; EXCEPTION WHEN OTHERS THEN NULL; END $$;
ALTER PUBLICATION supabase_realtime ADD TABLE solnechnaya_messages;

-- ============================================================
-- 4. STORAGE BUCKETS
-- ============================================================

INSERT INTO storage.buckets (id, name, public) VALUES ('wintozo-avatars', 'wintozo-avatars', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('wintozo-voice',   'wintozo-voice',   true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('wintozo-photos',  'wintozo-photos',  true) ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 5. STORAGE POLICIES
-- ============================================================

-- --- wintozo-avatars ---
DROP POLICY IF EXISTS "wintozo_avatars_read"   ON storage.objects;
DROP POLICY IF EXISTS "wintozo_avatars_insert" ON storage.objects;
DROP POLICY IF EXISTS "wintozo_avatars_update" ON storage.objects;
DROP POLICY IF EXISTS "wintozo_avatars_delete" ON storage.objects;
CREATE POLICY "wintozo_avatars_read"   ON storage.objects FOR SELECT USING (bucket_id = 'wintozo-avatars');
CREATE POLICY "wintozo_avatars_insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'wintozo-avatars');
CREATE POLICY "wintozo_avatars_update" ON storage.objects FOR UPDATE USING (bucket_id = 'wintozo-avatars');
CREATE POLICY "wintozo_avatars_delete" ON storage.objects FOR DELETE USING (bucket_id = 'wintozo-avatars');

-- --- wintozo-voice ---
DROP POLICY IF EXISTS "wintozo_voice_read"   ON storage.objects;
DROP POLICY IF EXISTS "wintozo_voice_insert" ON storage.objects;
DROP POLICY IF EXISTS "wintozo_voice_update" ON storage.objects;
DROP POLICY IF EXISTS "wintozo_voice_delete" ON storage.objects;
CREATE POLICY "wintozo_voice_read"   ON storage.objects FOR SELECT USING (bucket_id = 'wintozo-voice');
CREATE POLICY "wintozo_voice_insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'wintozo-voice');
CREATE POLICY "wintozo_voice_update" ON storage.objects FOR UPDATE USING (bucket_id = 'wintozo-voice');
CREATE POLICY "wintozo_voice_delete" ON storage.objects FOR DELETE USING (bucket_id = 'wintozo-voice');

-- --- wintozo-photos ---
DROP POLICY IF EXISTS "wintozo_photos_read"   ON storage.objects;
DROP POLICY IF EXISTS "wintozo_photos_insert" ON storage.objects;
DROP POLICY IF EXISTS "wintozo_photos_update" ON storage.objects;
DROP POLICY IF EXISTS "wintozo_photos_delete" ON storage.objects;
CREATE POLICY "wintozo_photos_read"   ON storage.objects FOR SELECT USING (bucket_id = 'wintozo-photos');
CREATE POLICY "wintozo_photos_insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'wintozo-photos');
CREATE POLICY "wintozo_photos_update" ON storage.objects FOR UPDATE USING (bucket_id = 'wintozo-photos');
CREATE POLICY "wintozo_photos_delete" ON storage.objects FOR DELETE USING (bucket_id = 'wintozo-photos');

-- ============================================================
-- 6. ДОПОЛНИТЕЛЬНЫЕ КОЛОНКИ (на случай если таблицы уже существуют)
-- ============================================================

ALTER TABLE wintozo_users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE wintozo_users ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
ALTER TABLE wintozo_users ADD COLUMN IF NOT EXISTS banned BOOLEAN DEFAULT false;

UPDATE wintozo_users SET banned = false WHERE banned IS NULL;

-- Если wintozo_messages создана раньше без этих колонок:
ALTER TABLE wintozo_messages ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE wintozo_messages ADD COLUMN IF NOT EXISTS audio_url TEXT;

-- Если wintozo_groups создана раньше без avatar_url:
ALTER TABLE wintozo_groups ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- ============================================================
-- 7. БИТВА СМАЙЛИКОВ + PRO + ДОЛГОЕ НАЖАТИЕ
-- ============================================================

-- Счётчик последовательных дней активности
ALTER TABLE wintozo_users ADD COLUMN IF NOT EXISTS day_streak INTEGER DEFAULT 0;
ALTER TABLE wintozo_users ADD COLUMN IF NOT EXISTS last_login_date DATE;

-- Команды битвы смайликов
CREATE TABLE IF NOT EXISTS wintozo_battle_teams (
  emoji TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Кто за какой смайлик
CREATE TABLE IF NOT EXISTS wintozo_battle_users (
  username TEXT PRIMARY KEY REFERENCES wintozo_users(username) ON DELETE CASCADE,
  team_emoji TEXT NOT NULL REFERENCES wintozo_battle_teams(emoji) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- Очки за текущую неделю (понедельник — воскресенье)
CREATE TABLE IF NOT EXISTS wintozo_battle_scores (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL REFERENCES wintozo_users(username) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  text_score INTEGER DEFAULT 0,
  voice_score INTEGER DEFAULT 0,
  image_score INTEGER DEFAULT 0,
  login_bonus INTEGER DEFAULT 0,
  total_score INTEGER DEFAULT 0,
  multiplier INTEGER DEFAULT 1, -- 1 или 2 (Pro)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(username, week_start)
);

-- История победителей
CREATE TABLE IF NOT EXISTS wintozo_battle_history (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  winning_emoji TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pro-подписки
CREATE TABLE IF NOT EXISTS wintozo_pro (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL REFERENCES wintozo_users(username) ON DELETE CASCADE,
  start_date TIMESTAMPTZ DEFAULT NOW(),
  end_date TIMESTAMPTZ,
  reason TEXT DEFAULT '', -- 'admin', 'battle', 'streak'
  UNIQUE(username)
);

-- Цвет сообщений (Pro)
ALTER TABLE wintozo_messages ADD COLUMN IF NOT EXISTS message_color TEXT DEFAULT '';
ALTER TABLE wintozo_group_messages ADD COLUMN IF NOT EXISTS message_color TEXT DEFAULT '';

-- Сообщения-ответы (reply_to)
ALTER TABLE wintozo_messages ADD COLUMN IF NOT EXISTS reply_to_id BIGINT;
ALTER TABLE wintozo_messages ADD COLUMN IF NOT EXISTS reply_text TEXT;
ALTER TABLE wintozo_messages ADD COLUMN IF NOT EXISTS reply_from TEXT;
ALTER TABLE wintozo_group_messages ADD COLUMN IF NOT EXISTS reply_to_id BIGINT;
ALTER TABLE wintozo_group_messages ADD COLUMN IF NOT EXISTS reply_text TEXT;
ALTER TABLE wintozo_group_messages ADD COLUMN IF NOT EXISTS reply_from TEXT;

-- Цвет сообщения пользователя (Pro)
ALTER TABLE wintozo_users ADD COLUMN IF NOT EXISTS message_color TEXT DEFAULT '';
ALTER TABLE wintozo_users ADD COLUMN IF NOT EXISTS admin_contacts_remaining INTEGER DEFAULT 2;
ALTER TABLE wintozo_users ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false;

-- Пометить админа
UPDATE wintozo_users SET is_admin = true WHERE username = 'Admin';

-- RLS
ALTER TABLE wintozo_battle_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE wintozo_battle_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE wintozo_battle_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE wintozo_battle_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE wintozo_pro ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "battle_teams_read" ON wintozo_battle_teams;
DROP POLICY IF EXISTS "battle_teams_write" ON wintozo_battle_teams;
DROP POLICY IF EXISTS "battle_users_read" ON wintozo_battle_users;
DROP POLICY IF EXISTS "battle_users_write" ON wintozo_battle_users;
DROP POLICY IF EXISTS "battle_scores_read" ON wintozo_battle_scores;
DROP POLICY IF EXISTS "battle_scores_write" ON wintozo_battle_scores;
DROP POLICY IF EXISTS "battle_history_read" ON wintozo_battle_history;
DROP POLICY IF EXISTS "pro_read" ON wintozo_pro;
DROP POLICY IF EXISTS "pro_write" ON wintozo_pro;

CREATE POLICY "battle_teams_read"  ON wintozo_battle_teams  FOR SELECT USING (true);
CREATE POLICY "battle_teams_write" ON wintozo_battle_teams  FOR INSERT WITH CHECK (true);
CREATE POLICY "battle_users_read"  ON wintozo_battle_users  FOR SELECT USING (true);
CREATE POLICY "battle_users_write" ON wintozo_battle_users  FOR ALL USING (true);
CREATE POLICY "battle_scores_read"  ON wintozo_battle_scores FOR SELECT USING (true);
CREATE POLICY "battle_scores_write" ON wintozo_battle_scores FOR ALL USING (true);
CREATE POLICY "battle_history_read" ON wintozo_battle_history FOR SELECT USING (true);
CREATE POLICY "pro_read"  ON wintozo_pro FOR SELECT USING (true);
CREATE POLICY "pro_write" ON wintozo_pro FOR ALL USING (true);

-- Вставка команд по умолчанию
INSERT INTO wintozo_battle_teams (emoji) VALUES
  ('🔥'), ('🚀'), ('👑'), ('🤖'), ('🎯'), ('💎'), ('🌟'), ('⚡')
ON CONFLICT (emoji) DO NOTHING;

-- ============================================================
-- 8. ФУНКЦИИ (RPC) для очков на сервере
-- ============================================================

-- Получить понедельник текущей недели
CREATE OR REPLACE FUNCTION get_week_start() RETURNS DATE AS $$
  SELECT DATE_TRUNC('week', CURRENT_DATE)::DATE;
$$ LANGUAGE SQL IMMUTABLE;

-- Добавить очки за сообщение (вызывается с клиента)
CREATE OR REPLACE FUNCTION add_message_points(
  p_username TEXT,
  p_message_type TEXT -- 'text', 'voice', 'image'
) RETURNS void AS $$
DECLARE
  v_week DATE;
  v_mult INTEGER := 1;
  v_team TEXT;
  v_points INTEGER;
  v_pro_end TIMESTAMPTZ;
BEGIN
  v_week := get_week_start();

  -- Проверить Pro
  SELECT end_date INTO v_pro_end FROM wintozo_pro WHERE username = p_username;
  IF v_pro_end IS NOT NULL AND v_pro_end > NOW() THEN
    v_mult := 2;
  END IF;

  -- Определить очки
  IF p_message_type = 'text' THEN
    v_points := 1;
  ELSIF p_message_type = 'voice' THEN
    v_points := 2;
  ELSIF p_message_type = 'image' THEN
    v_points := 5;
  ELSE
    v_points := 0;
  END IF;

  -- Проверить что пользователь в команде
  SELECT team_emoji INTO v_team FROM wintozo_battle_users WHERE username = p_username;
  IF v_team IS NULL THEN
    RETURN; -- не участвует в битве
  END IF;

  -- Вставить/обновить очки
  INSERT INTO wintozo_battle_scores (username, week_start, text_score, voice_score, image_score, total_score, multiplier)
  VALUES (
    p_username,
    v_week,
    CASE WHEN p_message_type = 'text' THEN v_points ELSE 0 END,
    CASE WHEN p_message_type = 'voice' THEN v_points ELSE 0 END,
    CASE WHEN p_message_type = 'image' THEN v_points ELSE 0 END,
    v_points * v_mult,
    v_mult
  )
  ON CONFLICT (username, week_start) DO UPDATE SET
    text_score = wintozo_battle_scores.text_score + CASE WHEN p_message_type = 'text' THEN v_points ELSE 0 END,
    voice_score = wintozo_battle_scores.voice_score + CASE WHEN p_message_type = 'voice' THEN v_points ELSE 0 END,
    image_score = wintozo_battle_scores.image_score + CASE WHEN p_message_type = 'image' THEN v_points ELSE 0 END,
    total_score = wintozo_battle_scores.total_score + v_points * v_mult,
    multiplier = v_mult;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Ежедневный вход (10 очков, 1 раз в день)
CREATE OR REPLACE FUNCTION claim_daily_login(p_username TEXT) RETURNS jsonb AS $$
DECLARE
  v_week DATE;
  v_today DATE := CURRENT_DATE;
  v_last_login DATE;
  v_streak INTEGER;
  v_team TEXT;
  v_mult INTEGER := 1;
  v_pro_end TIMESTAMPTZ;
BEGIN
  v_week := get_week_start();

  -- Получить последний вход
  SELECT last_login_date, day_streak INTO v_last_login, v_streak
  FROM wintozo_users WHERE username = p_username;

  -- Уже заходил сегодня?
  IF v_last_login = v_today THEN
    RETURN jsonb_build_object('claimed', false, 'reason', 'already_today');
  END IF;

  -- Обновить streak
  IF v_last_login = v_today - 1 THEN
    v_streak := COALESCE(v_streak, 0) + 1;
  ELSE
    v_streak := 1;
  END IF;

  UPDATE wintozo_users
  SET last_login_date = v_today, day_streak = v_streak
  WHERE username = p_username;

  -- Проверить Pro
  SELECT end_date INTO v_pro_end FROM wintozo_pro WHERE username = p_username;
  IF v_pro_end IS NOT NULL AND v_pro_end > NOW() THEN
    v_mult := 2;
  END IF;

  -- Проверить команду
  SELECT team_emoji INTO v_team FROM wintozo_battle_users WHERE username = p_username;
  IF v_team IS NOT NULL THEN
    INSERT INTO wintozo_battle_scores (username, week_start, login_bonus, total_score, multiplier)
    VALUES (p_username, v_week, 10, 10 * v_mult, v_mult)
    ON CONFLICT (username, week_start) DO UPDATE SET
      login_bonus = wintozo_battle_scores.login_bonus + 10,
      total_score = wintozo_battle_scores.total_score + 10 * v_mult,
      multiplier = v_mult;
  END IF;

  -- Проверить streak 15 дней → Pro на 10 дней
  IF v_streak >= 15 AND (v_streak % 15 = 0 OR v_streak = 15) THEN
    INSERT INTO wintozo_pro (username, end_date, reason)
    VALUES (p_username, NOW() + INTERVAL '10 days', 'streak')
    ON CONFLICT (username) DO UPDATE SET
      end_date = GREATEST(COALESCE(wintozo_pro.end_date, '1970-01-01'::TIMESTAMPTZ), NOW() + INTERVAL '10 days'),
      reason = 'streak';
  END IF;

  RETURN jsonb_build_object('claimed', true, 'streak', v_streak, 'mult', v_mult);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Выбрать/сменить команду
CREATE OR REPLACE FUNCTION join_battle_team(p_username TEXT, p_emoji TEXT) RETURNS jsonb AS $$
DECLARE
  v_exists TEXT;
BEGIN
  SELECT emoji INTO v_exists FROM wintozo_battle_teams WHERE emoji = p_emoji;
  IF v_exists IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'team_not_found');
  END IF;

  INSERT INTO wintozo_battle_users (username, team_emoji)
  VALUES (p_username, p_emoji)
  ON CONFLICT (username) DO UPDATE SET team_emoji = p_emoji, joined_at = NOW();

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Получить рейтинг команд за неделю
CREATE OR REPLACE FUNCTION get_battle_standings() RETURNS TABLE(
  emoji TEXT,
  total_points BIGINT,
  member_count BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    bu.team_emoji,
    COALESCE(SUM(bs.total_score), 0)::BIGINT AS total_points,
    COUNT(DISTINCT bu.username)::BIGINT AS member_count
  FROM wintozo_battle_users bu
  LEFT JOIN wintozo_battle_scores bs ON
    bs.username = bu.username AND
    bs.week_start = get_week_start()
  GROUP BY bu.team_emoji
  ORDER BY total_points DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Топ пользователей в команде за неделю
CREATE OR REPLACE FUNCTION get_team_top(p_emoji TEXT) RETURNS TABLE(
  username TEXT,
  total_score INTEGER,
  multiplier INTEGER
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    bu.username,
    COALESCE(bs.total_score, 0),
    COALESCE(bs.multiplier, 1)
  FROM wintozo_battle_users bu
  LEFT JOIN wintozo_battle_scores bs ON
    bs.username = bu.username AND
    bs.week_start = get_week_start()
  WHERE bu.team_emoji = p_emoji
  ORDER BY COALESCE(bs.total_score, 0) DESC
  LIMIT 50;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Подвести итоги недели (вызывается при загрузке в понедельник)
CREATE OR REPLACE FUNCTION settle_battle_week() RETURNS jsonb AS $$
DECLARE
  v_last_week DATE := get_week_start() - INTERVAL '7 days';
  v_last_end DATE := get_week_start() - INTERVAL '1 day';
  v_winner TEXT;
  v_already BOOLEAN;
BEGIN
  -- Уже подведены?
  SELECT EXISTS(SELECT 1 FROM wintozo_battle_history WHERE week_start = v_last_week) INTO v_already;
  IF v_already THEN
    RETURN jsonb_build_object('settled', false, 'reason', 'already');
  END IF;

  -- Найти победителя
  SELECT emoji INTO v_winner FROM (
    SELECT bu.team_emoji AS emoji, SUM(bs.total_score) AS total
    FROM wintozo_battle_users bu
    JOIN wintozo_battle_scores bs ON bs.username = bu.username AND bs.week_start = v_last_week
    GROUP BY bu.team_emoji
    ORDER BY total DESC
    LIMIT 1
  ) sub;

  IF v_winner IS NULL THEN
    RETURN jsonb_build_object('settled', false, 'reason', 'no_scores');
  END IF;

  -- Записать историю
  INSERT INTO wintozo_battle_history (week_start, week_end, winning_emoji)
  VALUES (v_last_week, v_last_end, v_winner);

  -- Победитель получает Pro на 3 дня
  -- Всем участникам команды-победителя
  INSERT INTO wintozo_pro (username, end_date, reason)
  SELECT bu.username, NOW() + INTERVAL '3 days', 'battle'
  FROM wintozo_battle_users bu
  WHERE bu.team_emoji = v_winner
  ON CONFLICT (username) DO UPDATE SET
    end_date = GREATEST(wintozo_pro.end_date, NOW() + INTERVAL '3 days'),
    reason = 'battle';

  -- Очистить старые очки
  DELETE FROM wintozo_battle_scores WHERE week_start < get_week_start();

  RETURN jsonb_build_object('settled', true, 'winner', v_winner);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Дать админу Pro навсегда
CREATE OR REPLACE FUNCTION ensure_admin_pro() RETURNS void AS $$
BEGIN
  INSERT INTO wintozo_pro (username, end_date, reason)
  VALUES ('Admin', NULL, 'admin')
  ON CONFLICT (username) DO UPDATE SET
    end_date = NULL,
    reason = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

SELECT ensure_admin_pro();

-- Получить Pro-статус пользователя
CREATE OR REPLACE FUNCTION get_pro_status(p_username TEXT) RETURNS jsonb AS $$
DECLARE
  v_pro_end TIMESTAMPTZ;
  v_reason TEXT;
  v_message_color TEXT;
  v_admin_contacts INTEGER;
BEGIN
  SELECT end_date, reason INTO v_pro_end, v_reason
  FROM wintozo_pro WHERE username = p_username;

  -- Админ всегда Pro
  IF p_username = 'Admin' THEN
    SELECT message_color INTO v_message_color FROM wintozo_users WHERE username = p_username;
    SELECT admin_contacts_remaining INTO v_admin_contacts FROM wintozo_users WHERE username = p_username;
    RETURN jsonb_build_object(
      'active', true, 'reason', 'admin', 'end_date', null,
      'message_color', COALESCE(v_message_color, ''),
      'admin_contacts', COALESCE(v_admin_contacts, 2)
    );
  END IF;

  IF v_pro_end IS NULL OR v_pro_end <= NOW() THEN
    RETURN jsonb_build_object('active', false);
  END IF;

  SELECT message_color INTO v_message_color FROM wintozo_users WHERE username = p_username;
  SELECT admin_contacts_remaining INTO v_admin_contacts FROM wintozo_users WHERE username = p_username;

  RETURN jsonb_build_object(
    'active', true,
    'reason', v_reason,
    'end_date', v_pro_end,
    'message_color', COALESCE(v_message_color, ''),
    'admin_contacts', COALESCE(v_admin_contacts, 2)
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Написать админу (Pro)
CREATE OR REPLACE function contact_admin(p_username TEXT) RETURNS jsonb AS $$
DECLARE
  v_remaining INTEGER;
BEGIN
  SELECT admin_contacts_remaining INTO v_remaining FROM wintozo_users WHERE username = p_username;
  IF COALESCE(v_remaining, 0) <= 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'no_contacts');
  END IF;
  UPDATE wintozo_users SET admin_contacts_remaining = admin_contacts_remaining - 1 WHERE username = p_username;
  RETURN jsonb_build_object('success', true, 'remaining', v_remaining - 1);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Обновить цвет сообщений (Pro)
CREATE OR REPLACE FUNCTION update_message_color(p_username TEXT, p_color TEXT) RETURNS void AS $$
BEGIN
  UPDATE wintozo_users SET message_color = p_color WHERE username = p_username;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Дать Pro пользователю (только админ)
CREATE OR REPLACE FUNCTION grant_pro(p_target_username TEXT, p_days INTEGER, p_admin_username TEXT, p_reason TEXT DEFAULT 'admin') RETURNS void AS $$
DECLARE
  v_days INTEGER;
  v_is_admin BOOLEAN;
BEGIN
  -- Проверить что вызывающий — админ
  SELECT is_admin INTO v_is_admin FROM wintozo_users WHERE username = p_admin_username;
  IF NOT v_is_admin THEN
    RAISE EXCEPTION 'Только админ может выдавать Pro';
  END IF;
  
  -- NULL дней = навсегда
  v_days := COALESCE(p_days, -1);
  
  INSERT INTO wintozo_pro (username, end_date, reason)
  VALUES (
    p_target_username,
    CASE WHEN v_days = -1 THEN NULL ELSE NOW() + (v_days || ' days')::INTERVAL END,
    COALESCE(p_reason, 'admin')
  )
  ON CONFLICT (username) DO UPDATE SET
    end_date = CASE WHEN v_days = -1 THEN NULL ELSE GREATEST(COALESCE(wintozo_pro.end_date, '1970-01-01'::TIMESTAMPTZ), NOW() + (v_days || ' days')::INTERVAL) END,
    reason = COALESCE(p_reason, 'admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Забрать Pro у пользователя (только админ)
CREATE OR REPLACE FUNCTION revoke_pro(p_target_username TEXT, p_admin_username TEXT) RETURNS void AS $$
DECLARE
  v_is_admin BOOLEAN;
BEGIN
  -- Проверить что вызывающий — админ
  SELECT is_admin INTO v_is_admin FROM wintozo_users WHERE username = p_admin_username;
  IF NOT v_is_admin THEN
    RAISE EXCEPTION 'Только админ может забирать Pro';
  END IF;
  
  DELETE FROM wintozo_pro WHERE username = p_target_username;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Очистить лишний Pro (кроме админа), если был выдан по ошибке
DELETE FROM wintozo_pro WHERE username != 'Admin' AND reason != 'admin';
-- Выдать админу Pro навсегда
SELECT ensure_admin_pro();

-- ============================================================
-- ГОТОВО!
-- ============================================================
